spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: #Your Email
    password: #your-app-password or your password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      accessSecret-key: FDBAB94A50DCF54E37FBB01D23CFED8192C6C94DCC31CAFE24F901F23B859680
      expiration: 10800000 # 3 hour
      refresh-token:
        refreshSecret-key: 622D8BD8A1601531103CF7B87C578EA001A29CABF2394F25B34DAA95C487726D
        expiration: 86400000  # 1 day
server:
  error:
    include-message: always


